name: Continuous Integration

on: [pull_request]

jobs:

  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node: [18]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - name: Installing project dependencies
      run: |
        yarn install --frozen-lockfile
    - name: Lint
      run: |
        yarn lint
    - name: Test
      run: |
        yarn test
    - name: Build Storybook
      run: |
        yarn story:build
    - name: Build Project
      run: |
        yarn build